# Generated by Django 4.0.7 on 2022-09-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherStation',
            new_name='Station',
        ),
    ]
