# Generated by Django 4.0.7 on 2022-09-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_rename_weatherdata_stationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdata',
            name='datetime',
            field=models.DateField(),
        ),
    ]
