# Generated by Django 4.0.7 on 2022-09-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_stationdata_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationdata',
            old_name='datetime',
            new_name='event_date',
        ),
    ]
